### ISSUE TITLE
Error while compiling package: react-native-maps-osmdroid:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by heronour** [fqborges/react-native-maps#2]
Hello, 
Is this pakage ready to use ? I got errors below :

`Task :react-native-maps-osmdroid:compileDebugJavaWithJavac FAILED
...\com\airbnb\android\react\maps\osmdroid\OsmMapView.java:34: error: cannot find symbo import org.osmdroid.views.CustomZoomButtonsController;
                         ^
  symbol:   class CustomZoomButtonsController
  location: package org.osmdroid.views
.....react-native-maps-osmdroid\lib\android\src\main\java\com\airbnb\android\react\maps\osmdroid\OsmMapView.java:116: error: package CustomZoomButtonsController does not exist
        this.getZoomController().setVisibility(CustomZoomButtonsController.Visibility.NEVER);
   `

**Comment by fqborges** [comment]
Yes, it is ready to use. I use this on for all my maps on my android apps. It probably is because of a changes from previous version. I think it is something similar to #1 

I did change a bit between RC0 and RC1 versions, now the default provider on Android is osmdroid, with a default version (6.0.3) chosen. This version can be changed using the project wide variable osmdroidVersion, e.g. { osmdroidVersion = '6.0.3' }, in your top-level build.gradle.

Please, verify what osmdroid version you have on the project. Despite the number, there are breaking changes between 6.01 (previous used version) and 6.0.3 (current version).

**Comment by heronour** [comment]
Ok, many thanks for your response, I have done this and it's correct but now I got this error:

`react-native-maps: osmdroid dependecy must be added to your app build.gradle to support osmdroid provider.`

I have put correctly the {osmdroidVersion = '6.0.3' },
On my view : 
```
import MapView,  { PROVIDER_OSMDROID } from 'react-native-maps-osmdroid';
// ...
<MapView
  provider={PROVIDER_OSMDROID }
...
>
```

**Comment by fqborges** [comment]
It seems you didn't link/install the package.

Please check if you have this lines:

-  on `android/app/build.gradle` :
```
dependencies {
   ...
   implementation project(':react-native-maps-osmdroid') 
   ...
}
```
-  on `android/settings.gradle` :
```
include ':react-native-maps-osmdroid'
project(':react-native-maps-osmdroid').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-maps-osmdroid/lib/android')
```
-  on `android/app/src/main/java/<your-package>/MainApplication.java` :
```
import com.airbnb.android.react.maps.MapsPackage;

public class MainApplication ... {
    ...
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
            ...
            new MapsPackage(),
            ...
      );
    }
...
}
```

**Comment by heronour** [comment]
Ok thank you @fqborges I will check 
Thanks a lot,

**Comment by heronour** [comment]
Thank you @fqborges it works it's great package!
