### ISSUE TITLE
Android Polygon onPress not working

### ISSUE THREAD

**Issue by capdilla** [fqborges/react-native-maps#23]
The event onPress in the Polygon Component is not working in android

**Comment by J0ANGARFLO** [comment]
I did not find a solution without affecting the original source code. Due to the project he worked on, an npm version had to be uploaded, this can be found at [@mvits/react-native-maps-osmdroid](https://www.npmjs.com/package/@mvits/react-native-maps-osmdroid)

The changes made are as follows:

* In the **Geojson.js** file in the path _\lib\components_. Add this `onPress={props.onPress}` after line 118 (Followed by `strokeWidth={props.strokeWidth}` in `MapView.Polygon`)
* In the **OsmMapView.java** file in the path _\lib\android\src\main\java\com\airbnb\android\react\maps\osmdroid_. Add:

> 1. `polygon.setOnClickListener(onPolygonClickListener);` on line 294 immediately after the line `polygonMap.put(polygon, polygonView);`
> 2. I made a clone of the `private Polyline.OnClickListener onPolylineClickListener` function but with `Polygon`, like this:

```
private Polygon.OnClickListener onPolygonClickListener = new Polygon.OnClickListener() {
    @Override
    public boolean onClick(Polygon polygon, MapView mapView, GeoPoint geoPoint) {
        WritableMap event = makeClickEventData(polygon.getPoints().get(0));
        event.putString("action", "polygon-press");
        manager.pushEvent(context, polygonMap.get(polygon), "onPress", event);
        return true;
    }
};
```

* To use the component, the onPress property is used for the Polygon or Geojson elements (which inherits from Polygon). Ex:

```
<Geojson
    key={geoJsonLot.features[0].properties.LOT_PK}
    geojson={geoJsonLot}
    strokeWidth={6}
    strokeColor="#c19a45"
    fillColor="rgba(255,0,0,0.5)"
    onPress={() => properties.onPressPolygon(geoJsonLot)} />
```

Finally, I clean the react native project with the lines: `react-native start --reset-cache` and I run again clean cleaning the **./gradlew** like this: `cd android && ./gradlew clean && cd .. && react-native run-android`

I hope this is useful to those who presented the same problem
